# Site settings
name: 吕雄
email: lvxiong7zg@outlook.com
author: 吕雄
url: http://lvxiong7zg.com
resume_site: http://lvxiong7zg.com/me/
github: https://github.com/lvxiong7zg/
baseurl: ""  #根目录
description: 安静 也是一种风骨
motto: 安静 也是一种风骨
banner: 朝向白云头，只身万里游。晚风拂两袖，千里一轻舟！
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: lvxiong7zg
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : lvxiogn7zg
